ieducar_1204:
  build: .
  environment:
    - CORE_EXT_CONFIGURATION_ENV=development
  ports:
    - "8001:80"
  volumes:
    - .:/home/ieducar/ieducar
  links:
    - postgres95
  container_name: ieducar_1204

postgres95:
  volumes:
    - /var/lib/postgresql/data
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - "5430:5432"
